import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from '@mui/material'
import { theme } from '@/styles/MuiTheme'
import Providers from '@/components/auth/Providers'
import './globals.css'

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
})

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'MEMOLEAF',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="ko">
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Providers>
               <ThemeProvider theme={theme}>{children}</ThemeProvider>
            </Providers>
         </body>
      </html>
   )
}
