import type { Metadata } from 'next'
import { Noto_Sans_KR, Nanum_Gothic, Nanum_Myeongjo, Nanum_Pen_Script, Do_Hyeon, Jua } from 'next/font/google'
import { NavBar } from '@/components/shared/Navbar'
import { ThemeProvider } from '@mui/material'
import { theme } from '@/styles/MuiTheme'
import Providers from './Providers'
import './globals.css'

export const notoSans = Noto_Sans_KR({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
})

export const nanumGothic = Nanum_Gothic({
  variable: '--font-nanum-gothic',
  subsets: ['latin'],
  weight: ['400'],
})

export const nanumMyeongjo = Nanum_Myeongjo({
  variable: '--font-nanum-myeongjo',
  subsets: ['latin'],
  weight: ['400'],
})

export const nanumPenScript = Nanum_Pen_Script({
  variable: '--font-nanum-pen-script',
  subsets: ['latin'],
  weight: ['400'],
})

export const doHyeon = Do_Hyeon({
  variable: '--font-do-hyeon',
  subsets: ['latin'],
  weight: ['400'],
})

export const jua = Jua({
  variable: '--font-jua',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'MEMOLEAF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSans.variable} antialiased`}>
        <Providers>
          <ThemeProvider theme={theme}>
            <NavBar />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
